# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'MX5BrowserOC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  
  pod 'Reachability', '~> 3.2'
  pod 'CocoaLumberjack', '~> 3.3.0'
  pod 'KYMenu'
  pod 'YYKit', '~> 1.0.9'

  # Pods for MX5BrowserOC

  target 'MX5BrowserOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MX5BrowserOCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
